<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.65.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.65.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColorGuesser.Shared\ColorGuesser.Shared.csproj" />
    <ProjectReference Include="..\ColorGuesser.Client\ColorGuesser.Client.csproj" />
  </ItemGroup>

</Project>
